### ISSUE TITLE
Не получаю данные уровня LogTrace, Debug в консольном приложении

### ISSUE THREAD

**Issue by XaspMe** [ernado-x/X.Extensions.Logging.Telegram#1]
Спасибо за вашу работу и статью на хабре!
Я столкнулся с проблемой получения данных уровня (LogTrace, Debug) через Телеграм в своем консольном приложении без использования конфига, возможно ли это?
Код был взят из примера в Readme

  {
      LogLevel = LogLevel.Debug,
  };

**Comment by ernado-x** [comment]
Добрый день!

Да, логи должны приходить. Можете пожалуйста выслать пример кода, в котором у вас не срабатывает отправка эти сообщений?
Для сообщений уровня Warning и Error отправка работает?

**Comment by XaspMe** [comment]
Я к сожалению не имею большого опыта работы с гитхабом и Isuue, поэтому разместил пример у себя и добавил комментарии:
https://github.com/XaspMe/Logging.Telegram.Send-Issue-Example - тут использован ваш код. В HostedService c конфигом все работает нормально.

**Comment by ernado-x** [comment]
Похоже я понял в чем проблема.

Ддйтсивтельн в этом примере не будут отображаться сообщения уровня Debug и Trace, так как минимальный уровень для всех логгеров  по умолчанию – Information.

Все сообщения  будут отображаться если чуть изменить код:

 

            var options = new TelegramLoggerOptions
            {
                AccessToken = "xxx",
                ChatId = "xxx",
                LogLevel = LogLevel.Trace //Set Trace level for TelegramLogger
            };
            
            var factory = LoggerFactory.Create(builder =>
                {
                    builder
                        .ClearProviders()
                        .SetMinimumLevel(LogLevel.Trace) //Set Trace level as minimum level for all loggers
                        .AddTelegram(options)
                        .AddConsole();
                }
            );

**Comment by XaspMe** [comment]
Это действительно работает. Спасибо!
