### ISSUE TITLE
problem sending telegram message with quotes

### ISSUE THREAD

**Issue by kitasvko** [ernado-x/X.Extensions.Logging.Telegram#4]
bug with quotes in telegram
example of log
Error during data gate api call: CallStoredProcedureAsync error: Could not find stored procedure 'dbo.t2s_exportPos_BIqwe'.\nStackTrace:\nat System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\nat System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\nat System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\nat System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean & dataReady)\nat System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\nat System.Data.SqlClient.SqlDataReader.get_MetaData()\nat System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\nat System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task & task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\nat System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task & task, Boolean & usedCache, Boolean asyncWrite, Boolean inRetry)\nat System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\nat System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\nat System.Data.SqlClient.SqlCommand.ExecuteReader()\nat DataGate.Service.Api.Helpers.SqlExecutionHelper.ExecuteStatement(ServiceCallInfo callInfo) in D:\\data-gate-project\\data-gate\\src\\DataGate.Service\\DataGate.Service.Api\\Helpers\\SqlExecutionHelper.cs:line\nOperatorGlobalKey: dx965dy

**Comment by ernado-x** [comment]
Fixed by #5
